### ISSUE TITLE
UnionType import error... Type exists only in Python 3.10

### ISSUE THREAD

**Issue by hazem-hamed** [avanov/openapi-client-generator#16]
Running `openapi-client-generator ` with Python v3.8.2 generates the following error. Looks like UnionType is introduced only in Python v3.10

```
inno-lnx:~> openapi-client-generator --help
Traceback (most recent call last):
  File "/ws/hahamed-sjc/pyats.dev/bin/openapi-client-generator", line 5, in <module>
    from openapi_client_generator.cli import main
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/openapi_client_generator/cli/__init__.py", line 3, in <module>
    from .main import main
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/openapi_client_generator/cli/main.py", line 6, in <module>
    from . import gen
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/openapi_client_generator/cli/gen.py", line 9, in <module>
    from openapi_type import parse_spec
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/openapi_type/__init__.py", line 10, in <module>
    from .custom_types import *
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/openapi_type/custom_types.py", line 4, in <module>
    import typeit
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/typeit/__init__.py", line 4, in <module>
    from .combinator.constructor import type_constructor, TypeConstructor
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/typeit/combinator/constructor.py", line 12, in <module>
    from ..parser import T, decide_node_type, OverrideT
  File "/ws/hahamed-sjc/pyats.dev/lib/python3.8/site-packages/typeit/parser/__init__.py", line 1, in <module>
    from types import UnionType
ImportError: cannot import name 'UnionType' from 'types' (/auto/pysw/cel7x/python64/3.8.2/lib/python3.8/types.py)
```

**Comment by avanov** [comment]
Yes, this is a known b/w incompatible change that I introduced a week ago in the current develop branch. You may want to limit the upper bound of `openapi-type` as it's where the breaking change was introduced (`in 0.2.0` https://pypi.org/project/openapi-type/#history)

**Comment by avanov** [comment]
I did it in line with https://github.com/avanov/openapi-client-generator/pull/15#issuecomment-1013523913 as there weren't many people using the package and personally I moved all my projects to Python 3.10 already. I'm happy to accept PRs with proper version boundaries to resolve the issue for versions prior 3.10.

**Comment by hazem-hamed** [comment]
Thanks @avanov for the quick response. I'll switch to master branch to avoid this issue.
